# Generated by Django 2.0.3 on 2019-09-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20190917_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='garage',
            new_name='garage_id',
        ),
    ]
