# Generated by Django 2.0.3 on 2019-09-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_auto_20190917_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='garage_id',
            new_name='garage',
        ),
    ]
